### ISSUE TITLE
Fail to initialize plugins

### ISSUE THREAD

**Issue by erictamura** [Advaith3600/PowerToys-Run-Currency-Converter#18]
Hello!

After installing the plugin and restarting PowerToys I get this error:

Plugins: Currency Converter - fail to load and would be disabled, please contact plugins creator for help

**Comment by Advaith3600** [comment]
Hi, thank you for informing this. Please provide me with more information and logs regarding the issue. You can find the log at `%LOCALAPPDATA%\Microsoft\PowerToys\PowerToys Run\Logs`. Additionally please mention if you have used the zip, or exe along with the version you are trying to install and the PowerToys version.

**Comment by erictamura** [comment]
Hello @Advaith3600.

PowerToys version: v0.84.1 (installed from MS Store)
CurrencyConverter: CurrencyConverter-1.2.0-x64.exe

A full reinstall solved the issue. 

FYI the log:

[2024-09-17 08:39:24.2426] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::55]
Starting PowerToys Run with PID=11908

[2024-09-17 08:39:24.2633] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::66]
Runner pid=25468

[2024-09-17 08:39:24.3957] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::108]
On Startup.

[2024-09-17 08:39:24.4390] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
ImageLoader.Initialize - Preload images cost <3ms>

[2024-09-17 08:39:24.4390] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Image\ImageLoader.cs::99]
Number of preload images is <93>, Images Number: 2, Unique Items 2

[2024-09-17 08:39:24.4819] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
|Wox.Infrastructure.Alphabet.Initialize|Preload pinyin cache <17ms>

[2024-09-17 08:39:24.4819] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Alphabet.cs::46]
Number of preload pinyin combination<0>

[2024-09-17 08:39:24.6098] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Calculator> is <1ms>

[2024-09-17 08:39:24.6098] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Folder> is <1ms>

[2024-09-17 08:39:24.6098] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <History> is <0ms>

[2024-09-17 08:39:24.6098] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Indexer> is <1ms>

[2024-09-17 08:39:24.6098] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <OneNote> is <0ms>

[2024-09-17 08:39:24.6098] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <PowerToys> is <1ms>

[2024-09-17 08:39:24.6523] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Program> is <35ms>

[2024-09-17 08:39:24.6523] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Registry> is <0ms>

[2024-09-17 08:39:24.6523] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Service> is <0ms>

[2024-09-17 08:39:24.6523] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Shell> is <4ms>

[2024-09-17 08:39:24.6523] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <System Commands> is <0ms>

[2024-09-17 08:39:24.6523] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Time and date> is <0ms>

[2024-09-17 08:39:24.6523] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Unit Converter> is <0ms>

[2024-09-17 08:39:24.6523] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Uri Handler> is <1ms>

[2024-09-17 08:39:24.6650] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <ValueGenerator> is <0ms>

[2024-09-17 08:39:24.6650] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <VS Code Workspaces> is <6ms>

[2024-09-17 08:39:24.6650] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Web Search> is <0ms>

[2024-09-17 08:39:24.6650] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Settings> is <0ms>

[2024-09-17 08:39:24.6863] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Terminal> is <11ms>

[2024-09-17 08:39:24.6863] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Window Walker> is <0ms>

[2024-09-17 08:39:24.7505] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::169]
-------------------------- Begin exception --------------------------
Message: Couldn't load assembly for Currency Converter in C:\Users\Cliente\AppData\Local\Microsoft\PowerToys\PowerToys Run\Plugins\CurrencyConverter\Community.PowerToys.Run.Plugin.CurrencyConverter.dll

Exception full name  : System.IO.FileLoadException
Exception message    : Could not load file or assembly 'Community.PowerToys.Run.Plugin.CurrencyConverter, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null'.
Exception stack trace:
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Wox.Plugin.PluginPair.CreatePluginInstance()
Exception source     : System.Private.CoreLib
Exception target site: System.Reflection.Assembly LoadFromAssemblyPath(System.String)
Exception HResult    : -2146232799
-------------------------- End exception --------------------------
