### ISSUE TITLE
v1.5.0 System.ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by ALERTua** [Advaith3600/PowerToys-Run-Currency-Converter#24]
```
Version: 0.87.1.0
OS Version: Microsoft Windows NT 10.0.22635.0
IntPtr Length: 8
x64: True
Date: 22.12.2024 11:51:23
Exception:
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.String.Join(String separator, String[] value)
   at Community.PowerToys.Run.Plugin.CurrencyConverter.Settings.GetAdditionalOptions()
   at Community.PowerToys.Run.Plugin.CurrencyConverter.Main.get_AdditionalOptions()
   at PowerLauncher.SettingsReader.<>c.<GetDefaultPluginsSettings>b__14_0(PluginPair x)
   at System.Linq.Enumerable.ListSelectIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at PowerLauncher.SettingsReader.UpdateSettings(PowerLauncherSettings settings)
   at PowerLauncher.SettingsReader..ctor(PowerToysRunSettings settings, ThemeManager themeManager)
   at PowerLauncher.App.<>c__DisplayClass20_0.<OnStartup>b__0()
   at Wox.Infrastructure.Stopwatch.Normal(String message, Action action)
   at PowerLauncher.App.OnStartup(Object sender, StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

deleting settings at `C:\Users\{USERNAME}\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Community.PowerToys.Run.Plugin.CurrencyConverter` didn't help

**Comment by Advaith3600** [comment]
Hi, thank you for reporting this now, Can you try this and let me know if it fixed the issue?


[CurrencyConverter-1.5.0-x64.zip](https://github.com/user-attachments/files/18221466/CurrencyConverter-1.5.0-x64.zip)
[CurrencyConverter-1.5.0-ARM64.zip](https://github.com/user-attachments/files/18221469/CurrencyConverter-1.5.0-ARM64.zip)

**Comment by Roan-V** [comment]
> Hi, thank you for reporting this now, Can you try this and let me know if it fixed the issue?
> 
> [CurrencyConverter-1.5.0-x64.zip](https://github.com/user-attachments/files/18221466/CurrencyConverter-1.5.0-x64.zip) [CurrencyConverter-1.5.0-ARM64.zip](https://github.com/user-attachments/files/18221469/CurrencyConverter-1.5.0-ARM64.zip)

Had the same issue
Can confirm this fixed it!

**Comment by Advaith3600** [comment]
Released https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/releases/tag/v1.5.1

**Comment by ALERTua** [comment]
v1.5.1 fixed the issue. thank you
